spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:9091

  profiles:
    active: default


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
