spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:9091

  profiles:
    active: default


#upload later on the git config
jwt:
  secret: 8T4qvY7nLm2ZxP9kHs6RwQ3eFd8BaJ5Nc1UvX0MgKe7TyI4OpLs9Dh2QrW6XeFa
  expiration: 86400000