server:
  port: 9091

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashvani80777/returnx-config-repo.git
          default-label: main
          clone-on-start: true
          timeout: 10
          username: ashvani80777



management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.core.env: DEBUG

test:
  username: ${GITHUB_USERNAME:NOT_FOUND}